drakkan/sftpgo

- config/config.go
- sftpd/server.go
as requested in https://github.com/pilif/sftpgo/commit/3ffe4a35fcf9300af82e1f3bcce89702c06b136d#commitcomment-34468605, this commit allows the user to configure the identification string used by the server. 
This is mostly a matter of vanity. I know of no real SSH client that's actually displaying this, but in my case, I felt like showing off :p
> make the server banner configurable

- dataprovider/dataprovider.go
- dataprovider/sqlcommon.go
as requested in https://github.com/pilif/sftpgo/commit/32192ce7b8515ef842f292ba6c7923a43235867e#commitcomment-34468602, this adds support to the bcrypt password encoding scheme when authenticating users.
Creating new users still uses Argon2i which is objectively better than bcrypt, but bcrypt is more widely used and thus some sites might still be stuck with bcrypt.
> add bcrypt support

- README.md
The README as shown on Github missed a leading curly brace. This is fixed with this PR
> Add missing newline, add code highlighting hint

- dataprovider/sqlite.go
When SQLite path starts with a `/`, we consider this to be an absolute path.
Eg.:
```json
{
"data_provider":{
"name":"/var/lib/sftpgo/sftpgo.db"
}
}
```
(This should maybe be reflected in the documentation?)
> When path starts with slash, consider it absolute

- init/sftpgo.service
Since we can now override settings through environment variables, it's handy to contain those changes in a separate file. This way, sysadmins can generate such a file without having to touch the systemd file.
Meanwhile the current flags are converted to `Environment` entries, which can be overridden in the `EnvironmentFile` if so desired.
If the file is not present, the directive [is ignored](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#EnvironmentFile=)
> Add Environment & EnvironmentFile directives

- init/sftpgo.service
By default on systems with systemd, send logs to stdout and thus to journald.
> Log to journald

- README.md
- in README.md use links to the files/folders in current branch (not master)
- fix OpenAPI 3 schema file link in README.md
> Use relative to the current branch links in readme

- README.md
- fail2ban/filters/sftpgo.conf
- fail2ban/jails/sftpgo.conf
Hello Drakkan, 
It's the first example of fail2ban configuration for sftpgo working with SystemD/JournalD.
```
~ # fail2ban-client status sftpgo                            
Status for the jail: sftpgo
|- Filter
|  |- Currently failed: 1
|  |- Total failed:     23
|  `- Journal matches:  _SYSTEMD_UNIT=sftpgo.service + _COMM=sftpgo
`- Actions
|- Currently banned: 1
|- Total banned:     4
`- Banned IP list:   197.248.10.108
```
Tested under real conditions :D
The filter can be improved.
> Add systemD/journalD sftpgo Fail2ban configuration

- dataprovider/dataprovider.go
Use os.Environ() as a base instead of empty variable. Currently the environment of executed external auth program only contains SFTPGO_AUTHD* variables and therefore the program lacks additional context when started.
> Expand environment variables for external auth program

- docker/sftpgo/debian/Dockerfile
Since SFTPGo is an SLL based application, it requires an CA signed certificate to be able to authenticate an SSL connection with AWS. 
This PR includes a package installation instruction which will provide to the Debian image a group CA certificates, so it will be possible to make SSL connections with AWS endpoints while using the S3 binding feature.
> CA certificate for Debian Docker image

- service/service.go
Default `data_provider.name` is `sftpgo.db`. Even if driver is `memory`, it checks existence of `sftpgo.db` file.
I set `data_provider.name` to empty string when start portable mode.
Fixes #73
> portable: set data_provider.name to empty

- docker/sftpgo/alpine/Dockerfile
- docker/sftpgo/alpine/docker-entrypoint.sh
It allows to start docker with other commands such as `portable`
`docker run ... sftpgo portable`
> docker: remove serve command from entrypoint in alpine

- README.md
- vfs/s3fs.go
- vfs/vfs.go
If `sftpgo` is running on an Amazon EC2 instance, it needs to use IAM roles.
It doesn't have explicit access token on EC2 instance. 
`AWS SDK for Go` has ability to use shared config state. It's recommend method for EC2 instances on `Specifying Credentials` section of [documentation](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html)
> s3: enable shared config state

- httpd/httpd_test.go
- httpd/web.go
- templates/user.html
- vfs/s3fs.go
- vfs/vfs.go
By default AWS SDK use part_size of 5 MB. 
For big files, it is not ideal case. 
For Hadoop, it is not uncommon to use 512 MB.
Note:
Editing existing configuration will requires to set this value
> s3: export PartSize parameter

- cmd/portable.go
- docs/portable-mode.md
I couldn't find a way to disable debug logs on portable mode.
I add a flag for it.
> add verbose flag for portable mode

- logger/logger.go
`Level()` creates new logger. It's not changing current one. Receiver isn't a pointer.
So changing log level isn't effective.
```golang
// Level creates a child logger with the minimum accepted level set to level.
func (l Logger) Level(lvl Level) Logger {
l.level = lvl
return l
}
```
> fix log level changing problem

- sftpd/server.go
"failed to accept an incoming connection" log level seems a little too high, it triggers on any TCP healthchecks on the sftp port (ex. healthcheck probes or network scan) 
Setting this as debug allows to stop logging these in non-verbose mode.
> sftpd: set failed connection loglevel to debug

- README.md
Fixes a very small typo in the README ("compabible" -> "compatible").
> Fix "compatible" typo in README.md

- docs/full-configuration.md
- sftpd/server.go
Adds a `password_disabled` bool config key to `sftpd`, which causes `PasswordCallback` to be left `nil`, thus disabling password auth.
Useful in pubkey-only setups.
> Allow disabling password authentication in sftpd

- docker/sftpgo/alpine/Dockerfile
- docker/sftpgo/debian/Dockerfile
To visualize the progress of the docker builds, I added the `-v` flags to the go commands.
> Set verbosity for go commands in docker build

- vfs/gcsfs.go
As suggested by @drakkan in #178, better mime type detection than used in the [google-cloud-go](https://github.com/googleapis/google-cloud-go/blob/master/storage/storage.go#L1004) underlying package.
Example which previously gave `application/zip` as mime type:
> GCS: improve mime-type detection

- cmd/install_windows.go
- cmd/portable.go
- cmd/root.go
- cmd/startsubsys.go
- config/config.go
- config/config_test.go
This PR is a major breaking change to how sftpgo accepts configuration files.
So far the `--config-file` flag (or `SFTPGO_CONFIG_FILE` env var) accepted a so called "config name", a file name without extension. Internally, Viper (the config library used under the hood) uses this config name to find a config file in various paths with various extensions.
This is not really useful to users though. They usually want to pass an known config file to sftpgo instead of a kind of search parameter.
This PR changes the behavior of the above mentioned flag (and env var): they accept an absolute path to a config file or a relative path (to the working directory of the process).
Fixes #236
> Accept a path in config file flag

- config/config.go
- config/config_test.go
- service/service.go
- telemetry/router.go
- telemetry/telemetry.go
This PR adds a brand new HTTP server to SFTPGo exposing the following endpoints:
- `/healthz`: for health checks
- `/metrics` for Prometheus metrics
- `/debug` for pprof
The code and configuration are identical to the same code found in the HTTP server, I just copied it over and simplified it a bit.
This PR does not address the following questions **on purpose**:
- what should happen to the same endpoints in the HTTP server? (IMHO they should be removed)
- potential refactoring of the configuration (eg. move the profiler enable flag under the telemetry config)
- should the telemetry server run for SFTP subsystem? (probably yes)
These questions should be addressed in separate PRs/issues.
This PR potentially fixes #244.
> feat: add new telemetry server

- vfs/s3fs.go
SFTP is based on UTF-8 filenames, so non-ASCII filenames get transported with utf-8 escaped character sequences.
At least for the S3fs provider, if such a file is stored in a nested path it cannot be used as the source for a rename operations.
This adds the necessary escaping of the path fragments.
@drakkan I'm not sure how testing is done (assuming it's manual as per the README). I created this one as the result of bug report and verified the change to be working against an AWS S3 bucket using german umlauts (eg `äöü`). Pls advise if there is something else that should be done for verification from my side.
> S3fs: Handle non-ascii filename in rename operations

- cmd/portable.go
- dataprovider/user.go
- httpd/webadmin.go
- httpd/webclient.go
- templates/webadmin/folder.html
- templates/webadmin/fsconfig.html
- templates/webadmin/user.html
- utils/utils.go
- vfs/filesystem.go
This PR is related to #449 (look there for further details).
Right now vfs implementations use numeric IDs (`vfs.*FilesystemProvider`).
These IDs are implementation specific and even hard-coded in some places (e.g. `templates/webadmin/fsconfig.html` or some of the commandline flags)
This can lead to ID clashes and makes it pretty much impossible to maintain custom vfs implementations outside the main sftpgo project:
- let's say I write a custom vfs wrapper around `s3fs`. I name it `vfs.SomeFilesystemProvider` and it gets ID#6 in my source tree.  
it ends up being too specific to my individual use case and thus won''t be accepted into the main sftpgo project.  
I keep maintaining it in a separate fork on github.
- the official sftpgo project later adds support for …
> vfs: introduced string Provider IDs

- examples/ldapauth/main.go
Support 'virtual' users who have no homeDirectory, uidNumber or gidNumber.
Permit read-only access by a user named "anonymous", with any password.
Assume a conventional DIT with users under ou=people,dc=example,dc=com.
Read the LDAP bindPassword from a file (not baked into the code).
Log progress and problems to syslog.
> Flesh out examples/ldapauth

- config/config.go
- config/config_test.go
Parse `AuthOptions.Scope` from `SFTPGO_PLUGINS__{{idx}}__AUTH_OPTIONS__SCOPE`
if set.
Fixes #595
> Parse auth plugin information from env

- init/sftpgo.service
We can tighten security by adding the following to the systemd service file. Please tell me if my assumptions are wrong somewhere - I tested this with my local setup and it works fine, this should not compromise any functionality while removing potentially hazardous capabilities.
* NoNewPrivileges: should never be needed
* DevicePolicy: only basics required
* PrivateDevices: only needs mounted stuff for file access anyhow, never devices or memory or whatever
* ProtectSystem: no need to change boot or other critical files
* RestrictAddressFamilies: INET and UNIX only, no need for any other address families
Thanks for this project, it's amazing.
Cheers!
> systemd-security: add some easy wins

- httpd/httpd_test.go
- httpd/internal_test.go
- httpd/server.go
301 MovedPermanently is cached by the browser which can
be annoying when it is is on base path like / while one
may reuse the domain (e.g. localhost) for other apps/tests.
Fixes #695
Signed-off-by: Jeremy Clerc <jeremy@clerc.io>
> httpd: webpath redirect using status found (302)

- httpd/httpd.go
- httpd/httpd_test.go
- httpd/server.go
This adds a `/robots.txt` response to disallow all well-behaved bots. This was raised by one of our InfoSec people; I spent a little time disagreeing with them on the security aspect of `robots.txt` as bad actors and bad bots do not care about `/robots.txt`. They say you shouldn't wrestle a pig in mud, you both get dirty, and the pig likes it.
> chore: disallow all crawlers with robots.txt

- httpd/httpd_test.go
- vfs/statvfs_unix.go
I noticed that the `golangci-lint` step was failing on `main`, ran it locally, and have fixed a few things it was raising:
```
❯ golangci-lint run
httpd/httpd_test.go:121:2: `robotsTxtPath` is unused (deadcode)
robotsTxtPath                   = "/robots.txt"
^
vfs/statvfs_unix.go:22:18: unnecessary conversion (unconvert)
Bavail:  uint64(stat.Bavail),
^
vfs/statvfs_unix.go:24:18: unnecessary conversion (unconvert)
Ffree:   uint64(stat.Ffree),
^
vfs/statvfs_unix.go:25:18: unnecessary conversion (unconvert)
Favail:  uint64(stat.Ffree), // not sure how to calculate Favail
^
```
Also made use of the existing `healtzPath` value in `TestHealthCheck` for consistency with other tests using the value.
> chore: fix a linting error

- dataprovider/user.go
- httpd/webadmin.go
- templates/webadmin/admins.html
- templates/webadmin/users.html
Hi 👋 
Sometimes it's nice to have visibility into MFA status of admins and users.
Admins:
Users:
@drakkan - currently, users show as either `Enabled` or `-`. Do you think it might be better to show what protocols MFA is enabled for each user? 🤔
> feat: make MFA status visible in WebAdmin

- config/config.go
- docs/full-configuration.md
- docs/oidc.md
- httpd/oidc.go
- sftpgo.json
In order to request additional information for user creation the OAuth scopes should be configurable and not hardcoded.
Otherwise the existing (default) scopes needs to be extended which would provide the information to other OAuth apps requesting the scope as well. This is not intended.
Please let me know if I missed something.
> OIDC: Allow Scope to be configured

- vfs/s3fs.go
Remove AWS SDK Transport ResponseHeaderTimeout (finer-grained timeout are already handled by the callers)
Lower the threshold for MultipartCopy (5GB -> 500MB) to improve copy performance and reduce chance of hitting Single part copy timeout
Fixes #898
> Fix timeout error when renaming large files

- openapi/openapi.yaml
This change is linked to https://github.com/drakkan/sftpgo/issues/1101 and should partially alleviate the need to change the content type in the files generated by openapi-generator-cli
Signed-off-by: Jon Bendtsen <github@jonb.dk>
> Added charset=utf-8 to application/json content type

- docker/README.md
Describing how to use the graceful shutdown period in a docker SFTPGO container and giving some examples of what happens with both existing and new connections.
Signed-off-by: Jon Bendtsen <github@jonb.dk>
> Added graceful shutdown description to docker

- docker/README.md
Dockers default grace period is only 10 seconds, so added a warning to alert users to those cases where their SFTPGO_GRACE_TIME is larger than the docker grace
> Add warning of docker grace vs. SFTPGo grace

- docs/metrics.md
I do not know which version removed /metrics from the HTTP server, but it does not seem to be available in 2.4.2, so I updated the metrics documentation to reflect this. Replaced with links to telemetry configuration.
Signed-off-by: Jon Bendtsen <github@jonb.dk>
> metrics only available in telemetry server

- examples/ldapauth/main.go
- examples/ldapauthserver/httpd/ldapauth.go
This fixes an ldap injection in the ldapauth examples.
I can't immediately come up an example how (if at all) this could be exploited.
However, that sentence is a prime candidate for a list of "famous last words", so it should probably be fixed nonetheless.
> Fix potential ldap injection

- docs/external-auth.md
- internal/dataprovider/dataprovider.go
This allows an `external_auth_hook` program to send messages to the sftpgo logs.
Any output on stderr is logged with a special sender ("external_auth_hook") at severity warning.
My use-case is a deployment using docker, where syslog is not available. The change should be backwards compatible and the [ldapauth example](https://github.com/drakkan/sftpgo/tree/main/examples/ldapauth) automatically falls back to stderr when syslog is unavailble, so this fits nicely.
Thanks a lot for this tremendous piece of software! :heart:
> Send output from external_auth_hook to logs

- internal/common/eventmanager.go
- internal/common/eventmanager_test.go
The check `checkEventConditionPatterns` returns after first match is true, which doesn't allow to check multiple wildcards inverse. 
This change allows in the event rules to set multiple path filters with **inverse matches**. 
Which allows for matching to any kind of file except for those inverse matches (acts as an exclusions list).
All tests on the eventmanager_test.go passed.
Probably doesn't work with mixed path filters. Which I think does not make sense anyway, because a matching pattern always exclude any other inverse matches.
* update function checkEventConditionPatterns for multiple inverse patterns
* Use the _matches_ variable to keep track of the state if condition matches pattern. 
* extend TestDoubleStarMatching with inverse flag
* write test for multiple douple start …
> check for multiple inverse matches

- docs/custom-actions.md
- docs/data-retention-hook.md
- docs/post-connect-hook.md
- docs/post-disconnect-hook.md
- docs/post-login-hook.md
Before, it wasn't really clear where clients were configured and that their configuration also affected headers.
> Expand reference to http clients in hooks docs

- internal/config/config.go
- internal/dataprovider/dataprovider.go
This Pull Request introduces a feature that allows a file to be mounted for the data provider’s username and password. This is especially useful when using Docker secrets.
config:
```json
{
"data_provider": {
"username_file": "/path/to/file",
"password_file": "/path/to/file",
}
}
```
env:
```env
SFTPGO_DATA_PROVIDER__USERNAME_FILE="/path/to/file"
SFTPGO_DATA_PROVIDER__PASSWORD_FILE="/path/to/file"
```
> provider: support for username and password file

- docs/full-configuration.md
- internal/common/defender.go
- internal/common/defenderdb.go
- internal/common/defendermem.go
This PR implements optional log messages for defender events and the final ban of IPs. They can be enabled with the new config parameter `log_events: true` in the defender configuration struct.
Log Messages for invalid user and user with wrong credentials look like this:
```json
{"level":"info","time":"2023-12-19T10:04:39.093","sender":"defender","client_ip":"2a01:4f8::1","protocol":"FTP","event":"UserNotFound","increase_score_by":2,"score":2}
{"level":"info","time":"2023-12-19T10:04:45.360","sender":"defender","client_ip":"2a01:4f8::1","protocol":"FTP","event":"LoginFailed","increase_score_by":1,"score":3}
```
Log Messages when the score threshold is reached and the IP is banned:
```json
{"level":"info","time":"2023-12-19T10:07:53.768","sender":"defender","client_ip":"2a01:4f8::1","protoc …
```
> defender: implement logging of events and bans

- internal/sftpd/cmd_unix.go
If sftpgo is already running as a non-root user and the UID/GID matches the current one, we can skip the syscall.
> fix using rsync if running sftpgo as non-root user
