- README.md
> with -> will

- dataprovider/dataprovider.go
- dataprovider/sqlcommon.go
This will parse the public key field as a newline delimited list of public keys.
Return (valid) result on first match.
This should fix #14
> Support multiple public keys

- sftpd/handler.go
This will add extra quotes to some strings (or whatever else the variable might contain)
Signed-off-by: Jo Vandeginste <Jo.Vandeginste@kuleuven.be>
> Add quotes to certain strings

- api/api_test.go
- api/quota.go
- cmd/serve.go
- config/config.go
- dataprovider/bolt.go
- dataprovider/dataprovider.go
- dataprovider/mysql.go
- dataprovider/pgsql.go
- dataprovider/sqlcommon.go
- dataprovider/sqlite.go
- logger/logger.go
- sftpd/handler.go
- sftpd/scp.go
- sftpd/server.go
- sftpd/sftpd.go
- sftpd/sftpd_test.go
- sftpd/transfer.go
- utils/umask_unix.go
- utils/umask_windows.go
- utils/utils.go
I tried to add connectionID to any default logging - not to console logs
Signed-off-by: Jo Vandeginste <Jo.Vandeginste@kuleuven.be>
> Add connectionID to as many entries as possible

- api/api_test.go
- api/quota.go
- cmd/serve.go
- config/config.go
- dataprovider/bolt.go
- dataprovider/dataprovider.go
- dataprovider/mysql.go
- dataprovider/pgsql.go
- dataprovider/sqlcommon.go
- dataprovider/sqlite.go
- logger/logger.go
- sftpd/handler.go
- sftpd/internal_test.go
- sftpd/scp.go
- sftpd/server.go
- sftpd/sftpd.go
- sftpd/sftpd_test.go
- sftpd/transfer.go
- utils/umask_unix.go
- utils/umask_windows.go
- utils/utils.go
> Show key info

- dataprovider/bolt.go
- dataprovider/dataprovider.go
- dataprovider/mysql.go
- dataprovider/pgsql.go
- dataprovider/sqlcommon.go
- dataprovider/sqlite.go
- dataprovider/sqlqueries.go
- sftpd/handler.go
- sftpd/scp.go
- sftpd/server.go
- sftpd/sftpd.go
* created a "Log" function for type "Connection"
* created a "log" function for type "Provider"
* replace logger calls to Log/log where possible
I also renamed PGSSQL to PGSQL, as this seemed to be a typo
Signed-off-by: Jo Vandeginste <Jo.Vandeginste@kuleuven.be>
> Refactor the logging system

- dataprovider/dataprovider.go
This adds support to the sha512crypt password encoding scheme when authenticating users.
> Added sha512crypt support

- service/service.go
Signed-off-by: Jo Vandeginste <Jo.Vandeginste@kuleuven.be>
> Log version when starting the daemon

- .gitignore
- README.md
Hi,
It's a suggestion, merge if you like it or close it ^_^
Have a good day
> Update README make dataprovider init more clear, add gitignore

- README.md
- config/config.go
- dataprovider/dataprovider.go
- sftpd/sftpd_test.go
- sftpgo.json
> Rename before_login_program to pre_login_program

- README.md
- docs/account.md
- docs/build-from-source.md
- docs/custom-actions.md
- docs/dynamic-user-mod.md
- docs/external-auth.md
- docs/full-configuration.md
- docs/google-cloud-storage.md
- docs/keyboard-interactive.md
- docs/logs.md
- docs/metrics.md
- docs/performance.md
- docs/portable-mode.md
- docs/rest-api.md
- docs/s3.md
- docs/service.md
- docs/web-admin.md
- sftpgo.json
These are a number of quick changes to split up the docs. A lot of work has to be done still. I suggest you squash my changes when you merge the PR, unless you cherry pick and rebase the whole history (feel free!)
> Improve the docs (wip)

- docker/sftpgo/debian/Dockerfile
- docker/sftpgo/debian/README.md
This adds a build arg to the Debian Dockerfile to be able to build latest master, the latest tag or a specific tag.
> Add a version build arg to the Debian Dockerfile.

- docker/sftpgo/alpine/Dockerfile
- docker/sftpgo/alpine/README.md
This adds a build arg to the Alpine Dockerfile to be able to build latest master, the latest tag or a specific tag.
> Add a version build arg to the Alpine Dockerfile.

- .github/workflows/quality.yml
- dataprovider/dataprovider.go
- dataprovider/user.go
What do think about adding code quality checkers for new PRs @drakkan?
[golangci-lint](https://github.com/golangci/golangci-lint) is a great tool and contains lots of linters.
It's little bit annoying at the beginning, but I think following conventions is important for open source projects. 
We can enable/disable some linters or specific checks. It's fully configurable.
This PR shows example usage with Github Actions.
[Example Run](https://github.com/enescakir/sftpgo/runs/626163373?check_suite_focus=true)
> add github action workflow for code quality

- .github/workflows/.editorconfig
- .github/workflows/docker.yml
- Dockerfile
This PR adds a Dockerfile to the project. It's largely based on my previous Go applications and the existing examples in the repo. It's not perfect though, so we might need some fine tuning in the future, particularly around volumes and configuration.
Open questions:
- What are backups? Are they supposed to be saved to persistent storage or are they only meaningful during the lifecycle of the application?
- Where does the credential path point? What's being read from there? (Existing dockerfiles contain no reference)
Currently the above settings can only be overridden from environment variables, because defaults are defined for them in env vars. (I think that's an acceptable compromise though).
I'll work with this image anyway, so I'll provide patches along the way.
The PR also adds a …
> Add Dockerfile and GitHub Actions workflow

- .github/workflows/docker.yml
Based on https://github.com/docker/build-push-action/issues/165#issuecomment-705558902
> Fix empty env context in nightly builds

- docs/keyboard-interactive.md
- examples/OTP/authy/README.md
Here I am again, with another typo fix 😅
> Fix typo in Twilio name

- common/actions.go
- common/actions_test.go
- common/connection.go
- common/transfer.go
This PR adds support for the feature explained in #186
The PR only adds an interface and refactors the minimal code necessary. Further refactoring might make sense in a subsequent PR.
Fixes #186
> Add support for custom action hooks

- httpd/router.go
> Add health check endpoint

- httpd/web.go
- templates/users.html
UI based cloning of an existing user. The "add user" screen is prepopulated with existing user data.
Resolves drakkan/sftpgo#225
> Feature: Clone existing user via web admin

- vfs/s3fs.go
Fixes #275
@trapped can you please try this patch with your S3 compatible backed?  The initial '/' prefix should be automatically removed when SFTPGo create/check a key.
Of course I gave you the attribution for this patch.
I was a bit confused sorry, for GCS and AzBlob backeds we can get the content-type when we list the keys, for S3 this is not possibile so we have to add the `/` suffix when creating directories so this is not compact code that we could remove. I added some comments to clarify this. Thank you for spotting this issue.
I pushed a similar fix for GCS, the main difference is that for GCS we can remove the check in future since we don't create anymore (since 1.2.x) directories with a trailing `/`.
> s3: don't paginate to find zero-byte-keyed dirs

- examples/php-activedirectory-http-server/README.md
Hi Nicola,
I apologize, I ended up not having as much time this weekend as I wanted to for writing this, so I'm not sure if this is where you'd like things to be as a starting point for inclusion in the examples area, but we can adjust if needed. The Youtube video was only uploaded a short while ago so it's higher quality versions are still being processed at the moment.
(I wasn't really sure on the folder name to use for this PR, so I ended up using one with "php" and "activedirectory" in the folder name which might be a little more descriptive, since I felt `sftpgo-ldap-http-server` might not make as much sense for others if they saw that listed in the examples folder, but I'm welcome to making any adjustments you feel would be helpful.
Thank you and I'm hoping this will help others in …
> Added in a first draft of the page related to sftpgo-ldap-http-server.

- docs/defender.md
> add documentation for defender scores

- cmd/portable.go
Hi drakkan. I need force-path-style so I can use portable with minio. What do you think? Thanks for sftpgo!
> Add --s3-force-path-style to portable

- Dockerfile
- Dockerfile.alpine
- Dockerfile.distroless
> Simplify sed commands in Dockerfile(s)

- httpd/oidc.go
- httpd/oidc_test.go
Some OIDC providers like AAD provides `roles` field with array type.
> Add role field array support

- docs/full-configuration.md
Suggestion based on the below changelog excerpt
> - Added a CLI command to reset the admin password.
> - Added a CLI command to check if the service is alive.
> Aligned help example with v2.5.0 output

- templates/webadmin/defender.html
- templates/webadmin/iplists.html
> webadmin: fix typo on webpages
